# Generated by Django 4.0.4 on 2022-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutive_act',
            name='act_pdf',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane_pdf',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='power_letter',
            name='power_letter_pdf',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='property_accreditation',
            name='document_pdf',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_pdf',
            field=models.BinaryField(),
        ),
    ]
