# Generated by Django 4.0.4 on 2022-05-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_alter_constitutive_act_act_pdf_alter_plane_plane_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutive_act',
            name='act_pdf',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane_pdf',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='power_letter',
            name='power_letter_pdf',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='property_accreditation',
            name='document_pdf',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_pdf',
            field=models.BinaryField(editable=True),
        ),
    ]
