# Generated by Django 4.0.4 on 2022-05-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_alter_location_photo_ubication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceedings',
            old_name='accreditation',
            new_name='id_accreditation',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='constitutive_act',
            new_name='id_constitutive_act',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='identification',
            new_name='id_identification',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='location',
            new_name='id_location',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='plane',
            new_name='id_plane',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='request',
            new_name='id_request',
        ),
        migrations.RenameField(
            model_name='proceedings',
            old_name='status',
            new_name='id_status',
        ),
    ]
