# Generated by Django 3.2.13 on 2022-05-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_rename_accreditation_proceedings_id_accreditation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedings',
            name='id_accreditation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_proceedings', to='capture.property_accreditation'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_constitutive_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitutive_act_proceedings', to='capture.constitutive_act'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_proceedings', to='capture.identification'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_proceedings', to='capture.location'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane_proceedings', to='capture.plane'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_proceedings', to='capture.request'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_proceedings', to='capture.status'),
        ),
    ]
