# Generated by Django 4.0.4 on 2022-05-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_auto_20220522_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedings',
            name='id_identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_proceedings', to='capture.identification_type'),
        ),
    ]
